# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/oneview-sdk-ruby/cli.rb'

Metrics/LineLength:
  Max: 150

Style/IndentationWidth:
  Width: 2

Style/VariableName:
  EnforcedStyle: snake_case
  Exclude:
    - 'lib/oneview-sdk-ruby/resource/*'

Style/MethodName:
  Exclude:
    - 'lib/oneview-sdk-ruby/resource/*'

Style/FileName:
  Exclude:
    - 'lib/oneview-sdk-ruby.rb'
    - 'bin/oneview-sdk-ruby'

Style/AlignParameters:
  Exclude:
    - 'lib/oneview-sdk-ruby/cli.rb'


Style/AccessorMethodName:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false
